baseURL: /
DefaultContentLanguage: en

params:
    businessname: 'SebAssaf'
    showLanguageSelector: true #true if bilingual site - false if unilingua
    font: ''
    usebasin: 'https://usebasin.com/f/d467e1937a2b' #endpoint for forms
    googlemap: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2801.1822497582402!2d-74.04084658423461!3d45.40566434536808!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc9363486fd137b%3A0x4a15fd8b3925e859!2sThe%20UPS%20Store!5e0!3m2!1sen!2sca!4v1595857348466!5m2!1sen!2sca' # Map code of Google
    cta:
        footer_heading_fr: 'French Footer Heading'
        footer_heading_en: 'English Footer Heading'
        cta_fr: 'French CTA'
        cta_en: 'Book a Call'
        businnessquote_en: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'
        businnessquote_fr: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'
    hours:
        hour1en: 'Mon to Fri - 8:00-17:00' #Footer Hours Line #1
        hour2en: 'Sat - On Call' #Footer Hours Line #2
        hour3en: 'Sun - On Call' #Footer Hours Line #3
        hour1fr: 'Lun - Ven - 8:00-17:00' #Footer Hours Line #1 in French / Leave empty if it does not apply
        hour2fr: 'Sam - Sur Appel' #Footer Hours Line #1 in French / Leave empty if it does not apply
        hour3fr: 'Dim - Sur Appel' #Footer Hours Line #1 in French / Leave empty if it does not apply
    social:
        facebook: ''
        twitter: ''
        pinterest: ''
        instagram: ''
    schema:
        type: ProfessionalService
        priceRange: $$$
        reservation: 'false'
        openinghour: 'Tu-Fr 13:00-16:00'
        logo: android-chrome-512x512
        image: img/og.jpg
        address: 8 rue principale sud,
        address2: '#103'
        city: Delson
        region: QC
        country: Canada
        postalcode: J5B 0A2
        phone: +1-514-730-0028
        email: sebassaf@gmail.com

languages:
  fr:
    languageCode: fr
    title: SebAssaf.com
    description: Site Tagline
    contentDir: content/fr
    menu:
      main:
        - name: À Propos
          url: '#about'
          weight: 1
        - name: Marketing
          url: '#marketing'
          weight: 2
        - name: Health
          url: /contact/
          weight: 3

  en:
    languageCode: en
    title: SebAssaf.com
    description: Site Tagline
    contentDir: content/en
    menu:
      main:
        - name: About
          url: '#about'
          weight: 1
        - name: Marketing
          url: '#marketing'
          weight: 2
        - name: Health
          url: '#health'
          weight: 3
        - name: Consulting
          url: '#consulting'
          weight: 4
        - name: Contact
          url: '#contact'
          weight: 5

gtm: ''
enableRobotsTXT: true
disableAliases: true
disableKinds:
  - taxonomy
  - taxonomyTerm

sitemap:
  changefreq: monthly
  filename: sitemap.xml

imaging:
  resampleFilter: box
  quality: 85
  anchor: smart