[context.production.environment]
  HUGO_VERSION = "0.76.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.76.4"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404
[[redirects]]
	from = "/support"
	to = "/?ubwc=tAwyWnWOX1lBjM29i3H334195-65727"
	status = 301

 
