[context.production.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.72.0"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404